using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HospitalAutomation.Domain.Enums
{
    public enum PoliclinicType
    {
        FamilyMedicine =1 ,
        Algology,
        Amatem,
        AnesthesiologyandReanimation,
        BrainandNerveSurgery,
        SurgicalOncology,
        PediatricSurgery,
        PediatricDentistry,
        PediatricEndocrinology,
        PediatricInfectiousDiseases,
        PediatricGastroenterology,
        ChildGeneticDiseases,
        PediatricChestDiseases,
        PediatricHematologyandOncology,
        PediatricImmunologyandAllergyDiseases,
        PediatricCardiovascularSurgery,
        PediatricCardiology,
        PediatricMetabolicDiseases,
        PediatricNephrology,
        ChildNeurology,
        PediatricRheumatology,
        ChildHealthandDiseases,
        PediatricUrology,
        ChildandAdolescentSubstanceandAlcoholAddiction,
        ChildandAdolescentMentalHealthandDiseases,
        SkinandVenerealDiseases,
        Dentistry,
        HandSurgery,
        Endodontics,
        EndocrinologyandMetabolismDiseases,
        InfectiousDiseasesandClinicalMicrobiology,
        PhysicalMedicineandRehabilitation,
        Gastroenterology,
        GastroenterologySurgery,
        TraditionalComplementaryMedicineUnit,
        DevelopmentalPediatrics,
        GeneralSurgery,
        Geriatrics,
        ThoracicSurgery,
        ChestDiseases,
        EyeDiseases,
        Hematology,
        InternalMedicine,
        ImmunologyandAllergyDiseases,
        OccupationalandOccupationalDiseases,
        GynecologicalOncologySurgery,
        GynecologyandObstetrics,
        CardiacSurgery,
        Cardiology,
        EarNoseThroatDiseases,
        Nephrology,
        Neonatologists,
        neurology,
        Nuclearmedicine,
        Orthodontics,
        OrthopedicsandTraumatology,
        Perinatology,
        Periodontology,
        PlasticReconstructiveandAestheticSurgery,
        ProsthodonticTreatment,
        RadiationOncology,
        RestorativeDentistry,
        Rheumatology,
        MentalHealthandDiseases,
        HealthBoardAdult,
        HealthBoardChildSpecialNeedsReport,
        QuitSmokingClinic,
        SportsMedicine,
        UnderwaterMedicineandHyperbaricMedicine,
        MedicalEcologyandHydroclimatology,
        MedicalGenetics,
        MedicalOncology,
        Urology,
        OralandMaxillofacialSurgery,
        OralDentalandMaxillofacialRadiology,
        Radiology



    }
}
